### ISSUE TITLE
部分链接失效，详情如下

### ISSUE THREAD

**Issue by Fengyuan-Shi** [batermj/data_sciences_campaign#2]
References of Awesome Computer Vision Public Datasets: 立体视觉
    立体视觉:Middlebury
    立体视觉:KITTI
References of Awesome Computer Vision Public Datasets：人脸检测和识别
    人脸检测:FDDB
    人脸识别:MegaFace
References of Awesome Computer Vision Public Datasets: 行人检测
    行人检测:USC
    行人检测:CVC
    行人检测:TUD
    行人检测:NICTA
    行人检测:ETH
    行人检测:MIT
    行人检测:INRIA
    行人检测:Daimler
    行人检测:Caltech
    SUNCG
References of Awesome 知识语料库
    语言知识库:WordNet
    语言知识库:FrameNet
    语言知识库:EDR
    语言知识库:北京大学综合型语言知识库
    语言知识库:知网
    语言知识库:概念层次网络
References of Awesome 开源篇章标注语料库
    篇章标注语料库:PDTB 篇章语料库
    篇章标注语料库:指代标注语料库 ARRAU
    篇章标注语料库:篇章结构图库 GraphBank
    篇章标注语料库:OntoNotes 语料库
    标注语料库:CASIA-CASSIL
    Switchboard-DAMSL 语料
References of Awesome 开源视频数据集
    Sports-1M
    Youtube-8M
    HUMOS
    Kinetics
    Google AVA
    Youtube-BB
    Open Images
    Facebook SOA (Sciences, Objects & Actions)
    Facebook motions dataset

**Comment by batermj** [comment]
Working on this issue now, will check one by one
